### ISSUE TITLE
pasting tabs fails on this url

### ISSUE THREAD

**Issue by cheater** [joshdick/tabclip#4]
Hi, when I try to "paste" the following URL, or a list of URLs where this is one of them, TabClip does not do anything.

`https://geizhals.at/?cat=tvlcd&xf=2454_3D-f%E4hig%7E2454_inkl.+3D-Brille%7E2454_passiv%7E3381_2018%7E34_3840x2160`

Let me know if you need any more info.

**Comment by Keith94** [comment]
Can confirm!

**Comment by joshdick** [comment]
This ended up being a problem with the library I was using to extract URLs from arbitrary text (the extension tries to handle pasting tags from arbitrary text that might have just one URL per line.) I switched to a simpler, regex-based library that doesn't have this issue and seems to work better.

**Comment by joshdick** [comment]
Just published this fix to the Chrome/Firefox extension galleries as v1.1.1.
